In [0]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 


#img = cv2.imread("noise.jpg",0)
img = cv2.imread("aaaa.jpg",0)      #eroded noiseless image(erosion after performing opening-closing on original)
img1 = cv2.imread("bbbb.jpg",0)       #dilation after performing opening-closing on original
img2 = cv2.imread("d.jpg",0)          #output of opening-closing


ret,thresh1 = cv2.threshold(img,127,255,cv2.THRESH_BINARY)

im = np.asarray(thresh1)

print (im.shape)

print (im)
# plt.imshow(im)
for i in range(0,310):
  for j in range(0,351):
    im[i][j]= 255 - im[i][j]
    if(im[i][j]!=0):
      im[i][j]=1
      
      

# im = np.pad(im, pad_width=1, mode='constant', constant_values=1)   

# img1 = cv2.imread("res_noise2.jpg",0)


# for i in range(0,310):
#   for j in range(0,351):
#       if(im[i][j]==1):
#           im[i][j]=0
#       elif(im[i][j]==0):
#           im[i][j]=1


# for i in range(0,310):
#   for j in range(0,351):
#     if(im[i][j]!=1):
#         print (im[i][j])

# print (im[200][2])

# plt.imshow(im)

# kernel = [[0,0,0],[0,0,0],[0,0,0]]         # WHITE = 0, BLACK = 1
# T=9
# kernel = np.array(kernel)
# print (kernel.shape)

# plt.imshow(im)

# im = np.pad(im, pad_width=1, mode='constant', constant_values=1)

# plt.imshow(im)

# print (im.shape)

# for x in range(1, 311):
#         for y in range(1, 352):
#             t = (im[x - 1, y - 1] * kernel[0, 0] + im[x - 1, y] * kernel[0, 1] + im[x - 1, y + 1] * kernel[0, 2] +
#                                 im[x, y - 1] * kernel[1, 0] + im[x, y] * kernel[1, 1] + im[x, y + 1] * kernel[1, 2] +
#                                 im[x + 1, y - 1] * kernel[2, 0] + im[x + 1, y] * kernel[2, 1] + im[x + 1, y + 1] * kernel[2, 2])
#             if(t>=T):
#                 im[x][y] = 0
#             else:
#                 im[x][y] = 1
                
# im1 = np.zeros(shape=(310, 351), dtype=int)

# for i in range(0,310):
#   for j in range(0,351):
#     im1[i][j] = im[i+1][j+1]
    
    

# print (im1.shape)    
                

(310, 351)
[[  0   0   0 ...   0 255 255]
 [  0   0   0 ...   0 255 255]
 [  0   0   0 ...   0 255 255]
 ...
 [  0   0   0 ...   0 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [0]:
# im1 = np.zeros(shape=(310, 351), dtype=int)
# for x in range(0, 308):
#         for y in range(0, 349):
#             if((im[x, y] == kernel[0, 0]) and (im[x, y+1] == kernel[0, 1]) and (im[x, y + 2] == kernel[0, 2]) and (im[x+1, y] == kernel[1, 0]) and (im[x+1, y+1] == kernel[1, 1]) and (im[x+1, y + 2] == kernel[1, 2]) and (im[x + 2, y] == kernel[2, 0]) and (im[x + 2, y+1] == kernel[2, 1]) and (im[x + 2, y + 2] == kernel[2, 2])):
#                 im[x, y] = 0
#                 im1[x, y] = 0
#             elif((im[x, y] == kernel[0, 0]) or (im[x, y+1] == kernel[0, 1]) or (im[x, y + 2] == kernel[0, 2]) or (im[x+1, y] == kernel[1, 0]) or (im[x+1, y+1] == kernel[1, 1]) or (im[x+1, y + 2] == kernel[1, 2]) or (im[x + 2, y] == kernel[2, 0]) or (im[x + 2, y+1] == kernel[2, 1]) or (im[x + 2, y + 2] == kernel[2, 2])):
#                 im[x, y] = 1
#                 im1[x, y] = 1
#             elif((im[x, y] != kernel[0, 0]) and (im[x, y+1] != kernel[0, 1]) and (im[x, y + 2] != kernel[0, 2]) and (im[x+1, y] != kernel[1, 0]) and (im[x+1, y+1] != kernel[1, 1]) and (im[x+1, y + 2] != kernel[1, 2]) and (im[x + 2, y] != kernel[2, 0]) and (im[x + 2, y+1] != kernel[2, 1]) and (im[x + 2, y + 2] != kernel[2, 2])):
#                 im[x, y] = 1
#                 im1[x, y] = 1
                
# plt.imsave("aaaa.jpg", im1)              
        
# im2 = np.zeros(shape=(310, 351), dtype=int)

# for x in range(0, 308):
#      for y in range(0, 349):
#          if((im[x, y] == kernel[0, 0]) and (im[x, y+1] == kernel[0, 1]) and (im[x, y + 2] == kernel[0, 2]) and (im[x+1, y] == kernel[1, 0]) and (im[x+1, y+1] == kernel[1, 1]) and (im[x+1, y + 2] == kernel[1, 2]) and (im[x + 2, y] == kernel[2, 0]) and (im[x + 2, y+1] == kernel[2, 1]) and (im[x + 2, y + 2] == kernel[2, 2])):
#              im[x,y] = 0
#              im2[x, y] = 0
#          elif((im[x, y] == kernel[0, 0]) or (im[x, y+1] == kernel[0, 1]) or (im[x, y + 2] == kernel[0, 2]) or (im[x+1, y] == kernel[1, 0]) or (im[x+1, y+1] == kernel[1, 1]) or (im[x+1, y + 2] == kernel[1, 2]) or (im[x + 2, y] == kernel[2, 0]) or (im[x + 2, y+1] == kernel[2, 1]) or (im[x + 2, y + 2] == kernel[2, 2])):
#               im[x, y] = 0
#               im2[x, y] = 0
#           elif((im[x, y] != kernel[0, 0]) and (im[x, y+1] != kernel[0, 1]) and (im[x, y + 2] != kernel[0, 2]) and (im[x+1, y] != kernel[1, 0]) and (im[x+1, y+1] != kernel[1, 1]) and (im[x+1, y + 2] != kernel[1, 2]) and (im[x + 2, y] != kernel[2, 0]) and (im[x + 2, y+1] != kernel[2, 1]) and (im[x + 2, y + 2] != kernel[2, 2])):
#               im[x, y] = 1
#               im2[x, y] = 1

# plt.imsave("b.jpg", im2)

# im3 = np.zeros(shape=(310, 351), dtype=int)                
# for x in range(0, 308):
#         for y in range(0, 349):
#             if((im[x, y] == kernel[0, 0]) and (im[x, y+1] == kernel[0, 1]) and (im[x, y + 2] == kernel[0, 2]) and (im[x+1, y] == kernel[1, 0]) and (im[x+1, y+1] == kernel[1, 1]) and (im[x+1, y + 2] == kernel[1, 2]) and (im[x + 2, y] == kernel[2, 0]) and (im[x + 2, y+1] == kernel[2, 1]) and (im[x + 2, y + 2] == kernel[2, 2])):
#                 im[x,y] = 0
#                 im3[x, y] = 0
#             elif((im[x, y] == kernel[0, 0]) or (im[x, y+1] == kernel[0, 1]) or (im[x, y + 2] == kernel[0, 2]) or (im[x+1, y] == kernel[1, 0]) or (im[x+1, y+1] == kernel[1, 1]) or (im[x+1, y + 2] == kernel[1, 2]) or (im[x + 2, y] == kernel[2, 0]) or (im[x + 2, y+1] == kernel[2, 1]) or (im[x + 2, y + 2] == kernel[2, 2])):
#                 im[x, y] = 0
#                 im3[x, y] = 0
#             elif((im[x, y] != kernel[0, 0]) and (im[x, y+1] != kernel[0, 1]) and (im[x, y + 2] != kernel[0, 2]) and (im[x+1, y] != kernel[1, 0]) and (im[x+1, y+1] != kernel[1, 1]) and (im[x+1, y + 2] != kernel[1, 2]) and (im[x + 2, y] != kernel[2, 0]) and (im[x + 2, y+1] != kernel[2, 1]) and (im[x + 2, y + 2] != kernel[2, 2])):
#                 im[x, y] = 1
#                 im3[x, y] = 1

                
# plt.imsave("c.jpg", im3)

# im4 = np.zeros(shape=(310, 351), dtype=int)
                
# for x in range(0, 308):
#         for y in range(0, 349):
#             if((im[x, y] == kernel[0, 0]) and (im[x, y+1] == kernel[0, 1]) and (im[x, y + 2] == kernel[0, 2]) and (im[x+1, y] == kernel[1, 0]) and (im[x+1, y+1] == kernel[1, 1]) and (im[x+1, y + 2] == kernel[1, 2]) and (im[x + 2, y] == kernel[2, 0]) and (im[x + 2, y+1] == kernel[2, 1]) and (im[x + 2, y + 2] == kernel[2, 2])):
#                 im[x,y] = 0
#                 im4[x, y] = 0
#             elif((im[x, y] == kernel[0, 0]) or (im[x, y+1] == kernel[0, 1]) or (im[x, y + 2] == kernel[0, 2]) or (im[x+1, y] == kernel[1, 0]) or (im[x+1, y+1] == kernel[1, 1]) or (im[x+1, y + 2] == kernel[1, 2]) or (im[x + 2, y] == kernel[2, 0]) or (im[x + 2, y+1] == kernel[2, 1]) or (im[x + 2, y + 2] == kernel[2, 2])):
#                 im[x, y] = 1
#                 im4[x, y] = 1
#             elif((im[x, y] != kernel[0, 0]) and (im[x, y+1] != kernel[0, 1]) and (im[x, y + 2] != kernel[0, 2]) and (im[x+1, y] != kernel[1, 0]) and (im[x+1, y+1] != kernel[1, 1]) and (im[x+1, y + 2] != kernel[1, 2]) and (im[x + 2, y] != kernel[2, 0]) and (im[x + 2, y+1] != kernel[2, 1]) and (im[x + 2, y + 2] != kernel[2, 2])):
#                 im[x, y] = 1
#                 im4[x, y] = 1
                
                
# plt.imsave("d.jpg", im4)


In [0]:
# plt.imshow(im)
im5 = np.zeros(shape=(310, 351), dtype=int)
im7 = np.zeros(shape=(310, 351), dtype=int)
im9 = np.zeros(shape=(310, 351), dtype=int)
# plt.imsave("noiseless.jpg", im)

ret1,thresh2 = cv2.threshold(img1,127,255,cv2.THRESH_BINARY)

im6 = np.asarray(thresh2)

for i in range(0,310):
  for j in range(0,351):
    im6[i][j]= 255 - im6[i][j]
    if(im6[i][j]!=0):
      im6[i][j]=1
      

# img2 = cv2.imread("res_noise2.jpg",0)

ret2,thresh3 = cv2.threshold(img2,127,255,cv2.THRESH_BINARY)

im8 = np.asarray(thresh3)

for i in range(0,310):
  for j in range(0,351):
    im8[i][j]= 255 - im8[i][j]
    if(im8[i][j]!=0):
      im8[i][j]=1
      

for i in range(0, 310):
        for j in range(0, 351):
            if((im8[i][j] - im[i][j]) < 0):           # noiseless image - eroded noiseless image
                im5[i][j] = 0
            elif((im8[i][j] - im[i][j]) == 0):
                im5[i][j] = 1
                
for i in range(0, 310):
        for j in range(0, 351):
            if((im8[i][j] - im6[i][j]) < 0):           # noiseless image - dilated noiseless image
                im7[i][j] = 0
            elif((im8[i][j] - im6[i][j]) == 0):
                im7[i][j] = 1
                
                
                
# for i in range(0, 310):
#         for j in range(0, 351):
# #             im7[i][j] = im2[i][j] - im4[i][j]         # opening(image) - closing(opening)
#             if((im2[i][j] - im4[i][j]) != 1):
#                  im7[i][j] = 1
#             elif((im2[i][j] - im4[i][j]) == 1):
#                  im7[i][j] = 0
            

# final = np.add(im7, im8)

for i in range(0, 310):                    
    for j in range(0, 351):
        if((im7[i][j]+im5[i][j])==2):
              im9[i][j] = 1
        elif((im7[i][j]+im5[i][j])==1):
              im9[i][j] = 0


                
# plt.imsave("bound1.jpg", im5)
plt.imsave("b1.jpg", im5)
plt.imsave("b2.jpg", im7)
plt.imsave("b1b2.jpg", im9)
# plt.imsave("boundfinal.jpg", im9)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:32: RuntimeWarning: overflow encountered in ubyte_scalars
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: overflow encountered in ubyte_scalars
